- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - StarlightBagel
  - Barratry
  - StarlightBox
  - StarlightCog
  - StarlightFland
  - StarlightHotel
  - Lobster
  - Manor
  - StarlightMarathon
  - StarlightMeta
  - StarlightOasis
  - StarlightOmega
  - Orwell
  - StarlightPacked
  - StarlightReach
  - StarlightSaltern
  - Starboard
  - StarlightElkridge
  
