- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - Barratry
  - StarlightCog
  - StarlightFland
  - Lobster
  - Manor
  - StarlightOasis
  - StarlightOmega
  - Orwell
  - StarlightReach
  - StarlightSaltern
  - Starboard

# - StarlightBagel
# - StarlightBox
# - StarlightHotel
# - StarlightMarathon
# - StarlightMeta
# - StarlightPacked
# - StarlightElkridge
# - StarlightElkridge