- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - StarlightCog
  - StarlightFland
  - Lobster
  - Manor
  - StarlightOasis
  - StarlightOmega
  - Orwell
  - StarlightReach

# - StarlightBagel
# - StarlightBox
# - StarlightHotel
# - StarlightMarathon
# - StarlightMeta
# - StarlightPacked
# - StarlightSaltern
# - Starboard
# - StarlightElkridge