- type: entity
  parent: [ClothingShoesBootsMagBase, BaseSecurityContraband, ClothingShoesMilitaryBase]
  id: ClothingShoesBootsMagSec
  name: security magboots
  description: A pair of standard magnetic boots, issued alongside the Security Hardsuit.
  components:
  - type: Sprite
    sprite: _Starlight/Clothing/Shoes/Boots/magboots-security.rsi
    state: icon
  - type: Clothing
    sprite: _Starlight/Clothing/Shoes/Boots/magboots-security.rsi
  - type: ClothingSpeedModifier
    walkModifier: 0.85
    sprintModifier: 0.8
  - type: Tag
    tags:
    - WhitelistChameleon
  - type: StaticPrice
    price: 350
