- type: antag
  id: Dragon
  name: roles-antag-dragon-name
  antagonist: true
  objective: roles-antag-dragon-objective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10800 # 3h STARLIGHT
