- type: entity
  name: double stun baton
  parent: Stunbaton
  id: DoubleStunbaton
  components:
  - type: Sprite
    sprite: _Starlight/Objects/Weapons/Melee/doublestunbaton.rsi
    layers:
    - state: stunbaton_off
      map: [ "enum.ToggleVisuals.Layer" ]
      
- type: entity
  name: purple stun baton
  parent: Stunbaton
  id: PurpleStunbaton
  components:
  - type: Sprite
    sprite: _Starlight/Objects/Weapons/Melee/purplestunbaton.rsi
    layers:
    - state: stunbaton_off
      map: [ "enum.ToggleVisuals.Layer" ]