name: Auto Assign Reviewers

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers based on labels
        uses: actions/github-script@v7
        with:
          script: |
            const labelToReviewer = {
              "Changes: Sprites": ["spriteReviewer"],
              "Changes: Map": ["PubliclyExecutedPig"],
              "Changes: UI": ["ss14-Starlight"],
              "Changes: Shaders": ["ss14-Starlight"],
              "Changes: Audio": ["ss14-Starlight"],
              "Changes: No C#": ["ss14-Starlight"],
            };

            const labels = context.payload.pull_request.labels.map(label => label.name);
            const reviewers = new Set();

            for (const label of labels) {
              const assignees = labelToReviewer[label];
              if (assignees) {
                assignees.forEach(a => reviewers.add(a));
              }
            }

            if (reviewers.size > 0) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: Array.from(reviewers),
              });
            }